/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

application {
    // Define the main class for the application.
    mainClass.set("per.nonlone.vertebra.App")
}

apply(plugin = "org.springframework.boot")


dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    // Hikari 连接池
    implementation("com.zaxxer:HikariCP")
    // MyBatisPlus ORM 框架增强
    implementation("com.baomidou:mybatis-plus-boot-starter:3.4.3")
    // MySQL 数据库连接
    runtimeOnly("mysql:mysql-connector-java")


    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}



